//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VelvetBrows
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientService1
    {
        public int ID { get; set; }
        public string Client { get; set; }
        public string Service { get; set; }
        public int StartTime { get; set; }
    }
}
